### ISSUE TITLE
Spring Data JPA의 deleteAll(), deleteAllInBatch() 

### ISSUE THREAD

**Issue by frorong** [esperar/dev.playground#10]
제가 알고있기론 deleteAll()은 모든 엔티티의 entry들을 순회하면서 delete를 호출하는 것으로 알고있어요.
deleteAllInBatch()는 한번에 삭제하는거라고 알고는 있는데. 정확히 어떻게 구현되어있는지는 잘 이해가 안가서요
그리고 왜 deleteAll()과 deleteAllInBatch()이렇게 두개로 나눈것일까요?

**Comment by rlaope** [comment]
영상 업로드 완료
