### ISSUE TITLE
리액티브 애플리케이션 WebFlux?

### ISSUE THREAD

**Issue by vumrra** [esperar/dev.playground#14]
리액티브 애플리케이션을 개발하기 위해 스프링 프래임워크 중 WebFlux를 활용할 수 있는 것으로 알고 있습니다.
하지만 자바 8에서 제공하는 CompletableFuture로도 비동기 처리를 구현할 수 있을 것 같은데, WebFlux를 선택하는 장점은 무엇인가요? Spring MVC에서 서블릿 구조를 사용하면서도 NIO나 톰캣의 비동기 처리를 사용할 수 있는 것으로 알고 있는데, Spring MVC와 WebFlux의 비동기 처리 모델을 비교해서 설명해주실 수 있을까요?

**Comment by rlaope** [comment]
제작 완료 https://www.youtube.com/watch?v=I9KECZPr5Bo
